### ISSUE TITLE
Script No Working - 'undefined'

### ISSUE THREAD

**Issue by pqhf5kd** [einhund/apple-music-local-lyrics#1]
Hello einhud
Is this script still working for you?

I've allowed Script Editor.app under Accessibility. 

I can see Music processing through the tracks, the Info box flashing up briefly, but no lyrics are added. 
Script Editor just states 'undefined' in the results view.

**Comment by einhund** [comment]
Thanks for your feedback. I've added following instructions for such cases to readme:

> For newer versions: Apple removed lyrics viewer from newer versions of Music app, where lyrics tab is missing from song info. Genius is the only available source. Change the following line to make the script work with Genius only:
> 
> ```
> const sources = [ "genius" ];
> ```
> 
> Also, lyrics added will NOT be visible anywhere on the new Music app, but the metadata will be added and lyrics will be shown on iPods.
> 
> You're welcome to [file a report to Apple](https://www.apple.com/feedback/apple-music.html) encouraging them to add this feature back. Your effort will be appreciated.

And there was an encoding issue in the old script file where `Info…` was incorrectly displayed as `Info¿`, please try again with the latest version.

**Comment by pqhf5kd** [comment]
Thank you for the fix.
The script is now working for me but I am seeing lyrics in the Get Info window and the Custom Lyrics checkbox is checked.
